/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Aug 25 19:01:29 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

	using System;
	using System.Collections;

	using Mono.Cecil;
	using Mono.Cecil.Cil;

	internal class ArrayDimensionCollection : IArrayDimensionCollection {

		private IList m_items;
		private ArrayType m_container;

		public event ArrayDimensionEventHandler OnArrayDimensionAdded;
		public event ArrayDimensionEventHandler OnArrayDimensionRemoved;

		public IArrayDimension this [int index] {
			get { return m_items [index] as IArrayDimension; }
			set { m_items [index] = value; }
		}

		public IArrayType Container {
			get { return m_container; }
		}

		public int Count {
			get { return m_items.Count; }
		}

		public bool IsSynchronized {
			get { return false; }
		}

		public object SyncRoot {
			get { return this; }
		}

		public ArrayDimensionCollection (ArrayType container)
		{
			m_container = container;
			m_items = new ArrayList ();
		}

		public void Add (IArrayDimension value)
		{
			if (OnArrayDimensionAdded != null && !this.Contains (value))
				OnArrayDimensionAdded (this, new ArrayDimensionEventArgs (value));
			m_items.Add (value);
		}

		public void Clear ()
		{
			if (OnArrayDimensionRemoved != null)
				foreach (IArrayDimension item in this)
					OnArrayDimensionRemoved (this, new ArrayDimensionEventArgs (item));
			m_items.Clear ();
		}

		public bool Contains (IArrayDimension value)
		{
			return m_items.Contains (value);
		}

		public int IndexOf (IArrayDimension value)
		{
			return m_items.IndexOf (value);
		}

		public void Insert (int index, IArrayDimension value)
		{
			if (OnArrayDimensionAdded != null && !this.Contains (value))
				OnArrayDimensionAdded (this, new ArrayDimensionEventArgs (value));
			m_items.Insert (index, value);
		}

		public void Remove (IArrayDimension value)
		{
			if (OnArrayDimensionRemoved != null && this.Contains (value))
				OnArrayDimensionRemoved (this, new ArrayDimensionEventArgs (value));
			m_items.Remove (value);
		}

		public void RemoveAt (int index)
		{
			if (OnArrayDimensionRemoved != null)
				OnArrayDimensionRemoved (this, new ArrayDimensionEventArgs (this [index]));
			m_items.Remove (index);
		}

		public void CopyTo (Array ary, int index)
		{
			m_items.CopyTo (ary, index);
		}

		public IEnumerator GetEnumerator ()
		{
			return m_items.GetEnumerator ();
		}
	}
}
