/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Tue Jul 05 15:48:32 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

	using System;
	using System.Collections;

	using Mono.Cecil;
	using Mono.Cecil.Cil;

	internal class AssemblyNameReferenceCollection : IAssemblyNameReferenceCollection {

		private IList m_items;
		private ModuleDefinition m_container;

		public IAssemblyNameReference this [int index] {
			get { return m_items [index] as IAssemblyNameReference; }
			set { m_items [index] = value; }
		}

		public IModuleDefinition Container {
			get { return m_container; }
		}

		public int Count {
			get { return m_items.Count; }
		}

		public bool IsSynchronized {
			get { return false; }
		}

		public object SyncRoot {
			get { return this; }
		}

		public AssemblyNameReferenceCollection (ModuleDefinition container)
		{
			m_container = container;
			m_items = new ArrayList ();
		}
		
		public void Add (IAssemblyNameReference value)
		{
			m_items.Add (value);
		}

		public void Clear ()
		{
			m_items.Clear ();
		}

		public bool Contains (IAssemblyNameReference value)
		{
			return m_items.Contains (value);
		}
		
		public int IndexOf (IAssemblyNameReference value)
		{
			return m_items.IndexOf (value);
		}

		public void Insert (int index, IAssemblyNameReference value)
		{
			m_items.Insert (index, value);
		}

		public void Remove (IAssemblyNameReference value)
		{
			m_items.Remove (value);
		}

		public void RemoveAt (int index)
		{
			m_items.Remove (index);
		}

		public void CopyTo (Array ary, int index)
		{
			m_items.CopyTo (ary, index);
		}

		public IEnumerator GetEnumerator ()
		{
			return m_items.GetEnumerator ();
		}

		public void Accept (IReflectionStructureVisitor visitor)
		{
			visitor.Visit (this);
			IAssemblyNameReference [] items = new IAssemblyNameReference [m_items.Count];
			m_items.CopyTo (items, 0);
			for (int i = 0; i < items.Length; i++)
				items [i].Accept (visitor);
		}
	}
}
