/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Mon Aug 15 17:55:17 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

	using System;
	using System.Collections;

	using Mono.Cecil;
	using Mono.Cecil.Cil;

	internal class CustomAttributeCollection : ICustomAttributeCollection, ILazyLoadableCollection {

		private IList m_items;
		private ICustomAttributeProvider m_container;
		private ReflectionController m_controller;

		private bool m_loaded;

		public ICustomAttribute this [int index] {
			get {
				return m_items [index] as ICustomAttribute;
			}
			set { m_items [index] = value; }
		}

		public ICustomAttributeProvider Container {
			get { return m_container; }
		}

		public int Count {
			get { return m_items.Count; }
		}

		public bool IsSynchronized {
			get { return false; }
		}

		public object SyncRoot {
			get { return this; }
		}

		public bool Loaded {
			get { return m_loaded; }
			set { m_loaded = value; }
		}

		public CustomAttributeCollection (ICustomAttributeProvider container)
		{
			m_container = container;
			m_items = new ArrayList ();
		}

		public CustomAttributeCollection (ICustomAttributeProvider container, ReflectionController controller) : this (container)
		{
			m_controller = controller;
		}

		public void Add (ICustomAttribute value)
		{
			m_items.Add (value);
		}

		public void Clear ()
		{
			m_items.Clear ();
		}

		public bool Contains (ICustomAttribute value)
		{
			return m_items.Contains (value);
		}

		public int IndexOf (ICustomAttribute value)
		{
			return m_items.IndexOf (value);
		}

		public void Insert (int index, ICustomAttribute value)
		{
			m_items.Insert (index, value);
		}

		public void Remove (ICustomAttribute value)
		{
			m_items.Remove (value);
		}

		public void RemoveAt (int index)
		{
			m_items.Remove (index);
		}

		public void CopyTo (Array ary, int index)
		{
			m_items.CopyTo (ary, index);
		}

		public IEnumerator GetEnumerator ()
		{
			return m_items.GetEnumerator ();
		}

		public void Load ()
		{
			if (m_controller != null && !m_loaded) {
				m_controller.Reader.VisitCustomAttributeCollection (this);
				m_loaded = true;
			}
		}

		public void Accept (IReflectionVisitor visitor)
		{
			visitor.VisitCustomAttributeCollection (this);
		}
	}
}
