/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Fri Aug 26 19:42:32 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

	using System;
	using System.Collections;

	using Mono.Cecil;
	using Mono.Cecil.Cil;

	internal class MemberReferenceCollection : IMemberReferenceCollection {

		private IList m_items;
		private ModuleDefinition m_container;

		public event MemberReferenceEventHandler OnMemberReferenceAdded;
		public event MemberReferenceEventHandler OnMemberReferenceRemoved;

		public IMemberReference this [int index] {
			get { return m_items [index] as IMemberReference; }
			set { m_items [index] = value; }
		}

		public IModuleDefinition Container {
			get { return m_container; }
		}

		public int Count {
			get { return m_items.Count; }
		}

		public bool IsSynchronized {
			get { return false; }
		}

		public object SyncRoot {
			get { return this; }
		}

		public MemberReferenceCollection (ModuleDefinition container)
		{
			m_container = container;
			m_items = new ArrayList ();
		}

		public void Add (IMemberReference value)
		{
			if (OnMemberReferenceAdded != null && !this.Contains (value))
				OnMemberReferenceAdded (this, new MemberReferenceEventArgs (value));
			m_items.Add (value);
		}

		public void Clear ()
		{
			if (OnMemberReferenceRemoved != null)
				foreach (IMemberReference item in this)
					OnMemberReferenceRemoved (this, new MemberReferenceEventArgs (item));
			m_items.Clear ();
		}

		public bool Contains (IMemberReference value)
		{
			return m_items.Contains (value);
		}

		public int IndexOf (IMemberReference value)
		{
			return m_items.IndexOf (value);
		}

		public void Insert (int index, IMemberReference value)
		{
			if (OnMemberReferenceAdded != null && !this.Contains (value))
				OnMemberReferenceAdded (this, new MemberReferenceEventArgs (value));
			m_items.Insert (index, value);
		}

		public void Remove (IMemberReference value)
		{
			if (OnMemberReferenceRemoved != null && this.Contains (value))
				OnMemberReferenceRemoved (this, new MemberReferenceEventArgs (value));
			m_items.Remove (value);
		}

		public void RemoveAt (int index)
		{
			if (OnMemberReferenceRemoved != null)
				OnMemberReferenceRemoved (this, new MemberReferenceEventArgs (this [index]));
			m_items.Remove (index);
		}

		public void CopyTo (Array ary, int index)
		{
			m_items.CopyTo (ary, index);
		}

		public IEnumerator GetEnumerator ()
		{
			return m_items.GetEnumerator ();
		}

		public void Accept (IReflectionVisitor visitor)
		{
			visitor.VisitMemberReferenceCollection (this);
		}
	}
}
