/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Mon Feb 14 22:21:15 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

    using System;
    using System.Collections;

    using Mono.Cecil;
    using Mono.Cecil.Cil;

    internal class MethodDefinitionCollection : IMethodDefinitionCollection, ILazyLoadableCollection {

        private IList m_items;
        private TypeDefinition m_container;

        private bool m_loaded;

        public IMethodDefinition this [int index] {
            get {
                m_container.Module.Loader.ReflectionReader.Visit (this);
                return m_items [index] as IMethodDefinition;
            }
            set { m_items [index] = value; }
        }

        public ITypeDefinition Container {
            get { return m_container; }
        }

        public int Count {
            get {
                m_container.Module.Loader.ReflectionReader.Visit (this);
                return m_items.Count;
            }
        }

        public bool IsSynchronized {
            get { return false; }
        }

        public object SyncRoot {
            get { return this; }
        }

        public bool Loaded {
            get { return m_loaded; }
            set { m_loaded = value; }
        }

        public MethodDefinitionCollection (TypeDefinition container)
        {
            m_container = container;
            m_items = new ArrayList ();
        }
        
        public void Add (IMethodDefinition value)
        {
            m_items.Add (value);
        }

        public void Clear ()
        {
            m_items.Clear ();
        }

        public bool Contains (IMethodDefinition value)
        {
            return m_items.Contains (value);
        }
        
        public int IndexOf (IMethodDefinition value)
        {
            m_container.Module.Loader.ReflectionReader.Visit (this);
            return m_items.IndexOf (value);
        }

        public void Insert (int index, IMethodDefinition value)
        {
            m_items.Insert (index, value);
        }

        public void Remove (IMethodDefinition value)
        {
            m_items.Remove (value);
        }

        public void RemoveAt (int index)
        {
            m_items.Remove (index);
        }

        public void CopyTo (Array ary, int index)
        {
            m_container.Module.Loader.ReflectionReader.Visit (this);
            m_items.CopyTo (ary, index);
        }

        public IEnumerator GetEnumerator ()
        {
            m_container.Module.Loader.ReflectionReader.Visit (this);
            return m_items.GetEnumerator ();
        }

        public void Accept (IReflectionVisitor visitor)
        {
            visitor.Visit (this);
            IMethodDefinition [] items = new IMethodDefinition [m_items.Count];
            m_items.CopyTo (items, 0);
            for (int i = 0; i < items.Length; i++)
                items [i].Accept (visitor);
        }
    }
}
