/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Sat May 14 20:51:45 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

    using System;
    using System.Collections;

    using Mono.Cecil;
    using Mono.Cecil.Cil;

    internal class ParameterDefinitionCollection : IParameterDefinitionCollection {

        private IList m_items;
        private MemberReference m_container;

        public IParameterDefinition this [int index] {
            get { return m_items [index] as IParameterDefinition; }
            set { m_items [index] = value; }
        }

        public IMemberReference Container {
            get { return m_container; }
        }

        public int Count {
            get { return m_items.Count; }
        }

        public bool IsSynchronized {
            get { return false; }
        }

        public object SyncRoot {
            get { return this; }
        }

        public ParameterDefinitionCollection (MemberReference container)
        {
            m_container = container;
            m_items = new ArrayList ();
        }
        
        public void Add (IParameterDefinition value)
        {
            m_items.Add (value);
        }

        public void Clear ()
        {
            m_items.Clear ();
        }

        public bool Contains (IParameterDefinition value)
        {
            return m_items.Contains (value);
        }
        
        public int IndexOf (IParameterDefinition value)
        {
            return m_items.IndexOf (value);
        }

        public void Insert (int index, IParameterDefinition value)
        {
            m_items.Insert (index, value);
        }

        public void Remove (IParameterDefinition value)
        {
            m_items.Remove (value);
        }

        public void RemoveAt (int index)
        {
            m_items.Remove (index);
        }

        public void CopyTo (Array ary, int index)
        {
            m_items.CopyTo (ary, index);
        }

        public IEnumerator GetEnumerator ()
        {
            return m_items.GetEnumerator ();
        }

        public void Accept (IReflectionVisitor visitor)
        {
            visitor.Visit (this);
            IParameterDefinition [] items = new IParameterDefinition [m_items.Count];
            m_items.CopyTo (items, 0);
            for (int i = 0; i < items.Length; i++)
                items [i].Accept (visitor);
        }
    }
}
