/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Sun Aug 28 03:06:26 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

	using System;
	using System.Collections;

	using Mono.Cecil;
	using Mono.Cecil.Cil;

	internal class PropertyDefinitionCollection : IPropertyDefinitionCollection {

		private IList m_items;
		private TypeDefinition m_container;

		public event PropertyDefinitionEventHandler OnPropertyDefinitionAdded;
		public event PropertyDefinitionEventHandler OnPropertyDefinitionRemoved;

		public IPropertyDefinition this [int index] {
			get { return m_items [index] as IPropertyDefinition; }
			set { m_items [index] = value; }
		}

		public ITypeDefinition Container {
			get { return m_container; }
		}

		public int Count {
			get { return m_items.Count; }
		}

		public bool IsSynchronized {
			get { return false; }
		}

		public object SyncRoot {
			get { return this; }
		}

		public PropertyDefinitionCollection (TypeDefinition container)
		{
			m_container = container;
			m_items = new ArrayList ();
		}

		public void Add (IPropertyDefinition value)
		{
			if (OnPropertyDefinitionAdded != null && !this.Contains (value))
				OnPropertyDefinitionAdded (this, new PropertyDefinitionEventArgs (value));
			m_items.Add (value);
		}

		public void Clear ()
		{
			if (OnPropertyDefinitionRemoved != null)
				foreach (IPropertyDefinition item in this)
					OnPropertyDefinitionRemoved (this, new PropertyDefinitionEventArgs (item));
			m_items.Clear ();
		}

		public bool Contains (IPropertyDefinition value)
		{
			return m_items.Contains (value);
		}

		public int IndexOf (IPropertyDefinition value)
		{
			return m_items.IndexOf (value);
		}

		public void Insert (int index, IPropertyDefinition value)
		{
			if (OnPropertyDefinitionAdded != null && !this.Contains (value))
				OnPropertyDefinitionAdded (this, new PropertyDefinitionEventArgs (value));
			m_items.Insert (index, value);
		}

		public void Remove (IPropertyDefinition value)
		{
			if (OnPropertyDefinitionRemoved != null && this.Contains (value))
				OnPropertyDefinitionRemoved (this, new PropertyDefinitionEventArgs (value));
			m_items.Remove (value);
		}

		public void RemoveAt (int index)
		{
			if (OnPropertyDefinitionRemoved != null)
				OnPropertyDefinitionRemoved (this, new PropertyDefinitionEventArgs (this [index]));
			m_items.Remove (index);
		}

		public void CopyTo (Array ary, int index)
		{
			m_items.CopyTo (ary, index);
		}

		public IEnumerator GetEnumerator ()
		{
			return m_items.GetEnumerator ();
		}

		public IPropertyDefinition [] GetProperties (string name)
		{
			ArrayList ret = new ArrayList ();
			foreach (IPropertyDefinition prop in this)
				if (prop.Name == name)
					ret.Add (prop);

			return ret.ToArray (typeof (IPropertyDefinition)) as IPropertyDefinition [];
		}

		public void Accept (IReflectionVisitor visitor)
		{
			visitor.VisitPropertyDefinitionCollection (this);
		}
	}
}
