/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Aug 25 19:01:29 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

	using System;
	using System.Collections;
	using System.Collections.Specialized;

	using Mono.Cecil;
	using Mono.Cecil.Cil;

	internal class TypeDefinitionCollection : NameObjectCollectionBase, ITypeDefinitionCollection {

		private IModuleDefinition m_container;

		public event TypeDefinitionEventHandler OnTypeDefinitionAdded;
		public event TypeDefinitionEventHandler OnTypeDefinitionRemoved;
	
		public ITypeDefinition this [int index] {
			get { return this.BaseGet (index) as ITypeDefinition; }
			set { this.BaseSet (index, value); }
		}

		public ITypeDefinition this [string fullName] {
			get { return this.BaseGet (fullName) as ITypeDefinition; }
			set { this.BaseSet (fullName, value); }
		}

		public IModuleDefinition Container {
			get { return m_container; }
		}

		public bool IsSynchronized {
			get { return (this as ICollection).IsSynchronized; }
		}

		public object SyncRoot {
			get { return (this as ICollection).SyncRoot; }
		}

		public TypeDefinitionCollection (IModuleDefinition container)
		{
			m_container = container;
		}

		public void Add (ITypeDefinition value)
		{
			if (value == null)
				throw new ArgumentNullException ("value");

			if (OnTypeDefinitionAdded != null && !this.Contains (value))
				OnTypeDefinitionAdded (this, new TypeDefinitionEventArgs (value));

			this.BaseSet (value.FullName, value);
		}

		public void Clear ()
		{
			if (OnTypeDefinitionRemoved != null)
				foreach (ITypeDefinition item in this)
					OnTypeDefinitionRemoved (this, new TypeDefinitionEventArgs (item));
			this.BaseClear ();
		}

		public bool Contains (ITypeDefinition value)
		{
			return Contains (value.FullName);
		}

		public bool Contains (string fullName)
		{
			return this.BaseGet (fullName) != null;
		}

		public int IndexOf (ITypeDefinition value)
		{
			return Array.IndexOf (this.BaseGetAllKeys (), value.FullName);
		}

		public void Remove (ITypeDefinition value)
		{
			if (OnTypeDefinitionRemoved != null && this.Contains (value))
				OnTypeDefinitionRemoved (this, new TypeDefinitionEventArgs (value));
			this.BaseRemove (value.FullName);
		}

		public void RemoveAt (int index)
		{
			if (OnTypeDefinitionRemoved != null)
				OnTypeDefinitionRemoved (this, new TypeDefinitionEventArgs (this [index]));
			this.BaseRemoveAt (index);
		}

		public void CopyTo (Array ary, int index)
		{
			(this as ICollection).CopyTo (ary, index);
		}

		public new IEnumerator GetEnumerator ()
		{
			return this.BaseGetAllValues ().GetEnumerator ();
		}

		public void Accept (IReflectionVisitor visitor)
		{
			visitor.VisitTypeDefinitionCollection (this);
		}
	}
}
