/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Mon Jan 10 00:16:44 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    [RId(0x21)]
    internal sealed class AssemblyProcessorTable : IMetadataTable {

        private RowCollection m_rows;

        public AssemblyProcessorRow this[int index] {
            get { return m_rows[index] as AssemblyProcessorRow; }
            set { m_rows[index] = value; }
        }

        public RowCollection Rows {
            get { return m_rows; }
            set { m_rows = value; }
        }

        public void Accept(IMetadataTableVisitor visitor) {
            visitor.Visit(this);
            this.Rows.Accept(visitor.GetRowVisitor());
        }
    }

    internal sealed class AssemblyProcessorRow : IMetadataRow {

        public static readonly int RowSize = 4;
        public static readonly int RowColumns = 1;

        [Column] private uint m_processor;

        public uint Processor {
            get { return m_processor; }
            set { m_processor = value; }
        }

        public int Size {
            get { return AssemblyProcessorRow.RowSize; }
        }

        public int Columns {
            get { return AssemblyProcessorRow.RowColumns; }
        }

        public void Accept(IMetadataRowVisitor visitor) {
            visitor.Visit(this);
        }
    }
}
