/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Feb 24 01:20:27 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    [RId (0x22)]
    internal sealed class AssemblyOSTable : IMetadataTable {

        private RowCollection m_rows;

        public AssemblyOSRow this [int index] {
            get { return m_rows [index] as AssemblyOSRow; }
            set { m_rows [index] = value; }
        }

        public RowCollection Rows {
            get { return m_rows; }
            set { m_rows = value; }
        }

        public void Accept (IMetadataTableVisitor visitor)
        {
            visitor.Visit (this);
            this.Rows.Accept (visitor.GetRowVisitor ());
        }
    }

    internal sealed class AssemblyOSRow : IMetadataRow {

        public static readonly int RowSize = 12;
        public static readonly int RowColumns = 3;

        private uint m_oSPlatformID;
        private uint m_oSMajorVersion;
        private uint m_oSMinorVersion;

        public uint OSPlatformID {
            get { return m_oSPlatformID; }
            set { m_oSPlatformID = value; }
        }

        public uint OSMajorVersion {
            get { return m_oSMajorVersion; }
            set { m_oSMajorVersion = value; }
        }

        public uint OSMinorVersion {
            get { return m_oSMinorVersion; }
            set { m_oSMinorVersion = value; }
        }

        public int Size {
            get { return AssemblyOSRow.RowSize; }
        }

        public int Columns {
            get { return AssemblyOSRow.RowColumns; }
        }

        public void Accept (IMetadataRowVisitor visitor)
        {
            visitor.Visit (this);
        }
    }
}
