/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Wed Jan 19 14:28:45 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    [RId (0x25)]
    internal sealed class AssemblyRefOSTable : IMetadataTable {

        private RowCollection m_rows;

        public AssemblyRefOSRow this [int index] {
            get { return m_rows [index] as AssemblyRefOSRow; }
            set { m_rows [index] = value; }
        }

        public RowCollection Rows {
            get { return m_rows; }
            set { m_rows = value; }
        }

        public void Accept (IMetadataTableVisitor visitor)
        {
            visitor.Visit (this);
            this.Rows.Accept (visitor.GetRowVisitor ());
        }
    }

    internal sealed class AssemblyRefOSRow : IMetadataRow {

        public static readonly int RowSize = 16;
        public static readonly int RowColumns = 4;

        [Column] private uint m_oSPlatformID;
        [Column] private uint m_oSMajorVersion;
        [Column] private uint m_oSMinorVersion;
        [Column] private uint m_assemblyRef;

        public uint OSPlatformID {
            get { return m_oSPlatformID; }
            set { m_oSPlatformID = value; }
        }

        public uint OSMajorVersion {
            get { return m_oSMajorVersion; }
            set { m_oSMajorVersion = value; }
        }

        public uint OSMinorVersion {
            get { return m_oSMinorVersion; }
            set { m_oSMinorVersion = value; }
        }

        public uint AssemblyRef {
            get { return m_assemblyRef; }
            set { m_assemblyRef = value; }
        }

        public int Size {
            get { return AssemblyRefOSRow.RowSize; }
        }

        public int Columns {
            get { return AssemblyRefOSRow.RowColumns; }
        }

        public void Accept (IMetadataRowVisitor visitor)
        {
            visitor.Visit (this);
        }
    }
}
