/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Feb 24 01:20:27 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    using Mono.Cecil;

    [RId (0x20)]
    internal sealed class AssemblyTable : IMetadataTable {

        private RowCollection m_rows;

        public AssemblyRow this [int index] {
            get { return m_rows [index] as AssemblyRow; }
            set { m_rows [index] = value; }
        }

        public RowCollection Rows {
            get { return m_rows; }
            set { m_rows = value; }
        }

        public void Accept (IMetadataTableVisitor visitor)
        {
            visitor.Visit (this);
            this.Rows.Accept (visitor.GetRowVisitor ());
        }
    }

    internal sealed class AssemblyRow : IMetadataRow {

        public static readonly int RowSize = 28;
        public static readonly int RowColumns = 9;

        private AssemblyHashAlgorithm m_hashAlgId;
        private ushort m_majorVersion;
        private ushort m_minorVersion;
        private ushort m_buildNumber;
        private ushort m_revisionNumber;
        private AssemblyFlags m_flags;
        private uint m_publicKey;
        private uint m_name;
        private uint m_culture;

        public AssemblyHashAlgorithm HashAlgId {
            get { return m_hashAlgId; }
            set { m_hashAlgId = value; }
        }

        public ushort MajorVersion {
            get { return m_majorVersion; }
            set { m_majorVersion = value; }
        }

        public ushort MinorVersion {
            get { return m_minorVersion; }
            set { m_minorVersion = value; }
        }

        public ushort BuildNumber {
            get { return m_buildNumber; }
            set { m_buildNumber = value; }
        }

        public ushort RevisionNumber {
            get { return m_revisionNumber; }
            set { m_revisionNumber = value; }
        }

        public AssemblyFlags Flags {
            get { return m_flags; }
            set { m_flags = value; }
        }

        public uint PublicKey {
            get { return m_publicKey; }
            set { m_publicKey = value; }
        }

        public uint Name {
            get { return m_name; }
            set { m_name = value; }
        }

        public uint Culture {
            get { return m_culture; }
            set { m_culture = value; }
        }

        public int Size {
            get { return AssemblyRow.RowSize; }
        }

        public int Columns {
            get { return AssemblyRow.RowColumns; }
        }

        public void Accept (IMetadataRowVisitor visitor)
        {
            visitor.Visit (this);
        }
    }
}
