/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Wed Jan 19 14:28:45 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    [RId (0x0d)]
    internal sealed class FieldMarshalTable : IMetadataTable {

        private RowCollection m_rows;

        public FieldMarshalRow this [int index] {
            get { return m_rows [index] as FieldMarshalRow; }
            set { m_rows [index] = value; }
        }

        public RowCollection Rows {
            get { return m_rows; }
            set { m_rows = value; }
        }

        public void Accept (IMetadataTableVisitor visitor)
        {
            visitor.Visit (this);
            this.Rows.Accept (visitor.GetRowVisitor ());
        }
    }

    internal sealed class FieldMarshalRow : IMetadataRow {

        public static readonly int RowSize = 8;
        public static readonly int RowColumns = 2;

        [Column] private MetadataToken m_parent;
        [Column] private uint m_nativeType;

        public MetadataToken Parent {
            get { return m_parent; }
            set { m_parent = value; }
        }

        public uint NativeType {
            get { return m_nativeType; }
            set { m_nativeType = value; }
        }

        public int Size {
            get { return FieldMarshalRow.RowSize; }
        }

        public int Columns {
            get { return FieldMarshalRow.RowColumns; }
        }

        public void Accept (IMetadataRowVisitor visitor)
        {
            visitor.Visit (this);
        }
    }
}
