/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Wed Jan 19 14:28:45 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    [RId (0x09)]
    internal sealed class InterfaceImplTable : IMetadataTable {

        private RowCollection m_rows;

        public InterfaceImplRow this [int index] {
            get { return m_rows [index] as InterfaceImplRow; }
            set { m_rows [index] = value; }
        }

        public RowCollection Rows {
            get { return m_rows; }
            set { m_rows = value; }
        }

        public void Accept (IMetadataTableVisitor visitor)
        {
            visitor.Visit (this);
            this.Rows.Accept (visitor.GetRowVisitor ());
        }
    }

    internal sealed class InterfaceImplRow : IMetadataRow {

        public static readonly int RowSize = 8;
        public static readonly int RowColumns = 2;

        [Column] private uint m_class;
        [Column] private MetadataToken m_interface;

        public uint Class {
            get { return m_class; }
            set { m_class = value; }
        }

        public MetadataToken Interface {
            get { return m_interface; }
            set { m_interface = value; }
        }

        public int Size {
            get { return InterfaceImplRow.RowSize; }
        }

        public int Columns {
            get { return InterfaceImplRow.RowColumns; }
        }

        public void Accept (IMetadataRowVisitor visitor)
        {
            visitor.Visit (this);
        }
    }
}
