/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Feb 24 01:20:28 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    using Mono.Cecil;

    [RId (0x08)]
    internal sealed class ParamTable : IMetadataTable {

        private RowCollection m_rows;

        public ParamRow this [int index] {
            get { return m_rows [index] as ParamRow; }
            set { m_rows [index] = value; }
        }

        public RowCollection Rows {
            get { return m_rows; }
            set { m_rows = value; }
        }

        public void Accept (IMetadataTableVisitor visitor)
        {
            visitor.Visit (this);
            this.Rows.Accept (visitor.GetRowVisitor ());
        }
    }

    internal sealed class ParamRow : IMetadataRow {

        public static readonly int RowSize = 8;
        public static readonly int RowColumns = 3;

        private ParamAttributes m_flags;
        private ushort m_sequence;
        private uint m_name;

        public ParamAttributes Flags {
            get { return m_flags; }
            set { m_flags = value; }
        }

        public ushort Sequence {
            get { return m_sequence; }
            set { m_sequence = value; }
        }

        public uint Name {
            get { return m_name; }
            set { m_name = value; }
        }

        public int Size {
            get { return ParamRow.RowSize; }
        }

        public int Columns {
            get { return ParamRow.RowColumns; }
        }

        public void Accept (IMetadataRowVisitor visitor)
        {
            visitor.Visit (this);
        }
    }
}
