/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Feb 24 01:20:28 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    [RId (0x01)]
    internal sealed class TypeRefTable : IMetadataTable {

        private RowCollection m_rows;

        public TypeRefRow this [int index] {
            get { return m_rows [index] as TypeRefRow; }
            set { m_rows [index] = value; }
        }

        public RowCollection Rows {
            get { return m_rows; }
            set { m_rows = value; }
        }

        public void Accept (IMetadataTableVisitor visitor)
        {
            visitor.Visit (this);
            this.Rows.Accept (visitor.GetRowVisitor ());
        }
    }

    internal sealed class TypeRefRow : IMetadataRow {

        public static readonly int RowSize = 12;
        public static readonly int RowColumns = 3;

        private MetadataToken m_resolutionScope;
        private uint m_name;
        private uint m_namespace;

        public MetadataToken ResolutionScope {
            get { return m_resolutionScope; }
            set { m_resolutionScope = value; }
        }

        public uint Name {
            get { return m_name; }
            set { m_name = value; }
        }

        public uint Namespace {
            get { return m_namespace; }
            set { m_namespace = value; }
        }

        public int Size {
            get { return TypeRefRow.RowSize; }
        }

        public int Columns {
            get { return TypeRefRow.RowColumns; }
        }

        public void Accept (IMetadataRowVisitor visitor)
        {
            visitor.Visit (this);
        }
    }
}
