/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Tue Mar 01 02:20:17 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    using Mono.Cecil;

    [RId (0x02)]
    public sealed class TypeDefTable : IMetadataTable {

        private RowCollection m_rows;

        public TypeDefRow this [int index] {
            get { return m_rows [index] as TypeDefRow; }
            set { m_rows [index] = value; }
        }

        public RowCollection Rows {
            get { return m_rows; }
            set { m_rows = value; }
        }

        internal TypeDefTable ()
        {
        }

        public void Accept (IMetadataTableVisitor visitor)
        {
            visitor.Visit (this);
            this.Rows.Accept (visitor.GetRowVisitor ());
        }
    }

    public sealed class TypeDefRow : IMetadataRow {

        public static readonly int RowSize = 24;
        public static readonly int RowColumns = 6;

        public TypeAttributes Flags;
        public uint Name;
        public uint Namespace;
        public MetadataToken Extends;
        public uint FieldList;
        public uint MethodList;

        internal TypeDefRow ()
        {
        }

        public void Accept (IMetadataRowVisitor visitor)
        {
            visitor.Visit (this);
        }
    }
}
