/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Sat Aug 20 17:28:12 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

	using System.Collections;

	public interface IConstructorCollection : ICollection, IReflectionVisitable {

		IMethodDefinition this [int index] { get; }

		ITypeDefinition Container { get; }

		void Add (IMethodDefinition value);
		void Clear ();
		bool Contains (IMethodDefinition value);
		int IndexOf (IMethodDefinition value);
		void Insert (int index, IMethodDefinition value);
		void Remove (IMethodDefinition value);
		void RemoveAt (int index);
	}
}
