/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Fri Feb 25 23:29:21 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

    using System.Collections;

    public interface ICustomAttributeCollection : ICollection, IReflectionVisitable {

        ICustomAttribute this [int index] { get; }

        ICustomAttributeProvider Container { get; }

        void Clear ();
        bool Contains (ICustomAttribute value);
        int IndexOf (ICustomAttribute value);
        void Insert (int index, ICustomAttribute value);
        void Remove (ICustomAttribute value);
        void RemoveAt (int index);
    }
}
