/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Aug 25 04:18:25 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

	using System;
	using System.Collections;

	public class ExternTypeEventArgs : EventArgs {

		private ITypeReference m_item;

		public ITypeReference ExternType {
			get { return m_item; }
		}

		public ExternTypeEventArgs (ITypeReference item)
		{
			m_item = item;
		}
	}

	public delegate void ExternTypeEventHandler (
		object sender, ExternTypeEventArgs ea);

	public interface IExternTypeCollection : ICollection, IReflectionVisitable {

		ITypeReference this [int index] { get; }
		ITypeReference this [string fullName] { get; }

		IModuleDefinition Container { get; }

		event ExternTypeEventHandler OnExternTypeAdded;
		event ExternTypeEventHandler OnExternTypeRemoved;

		void Add (ITypeReference value);
		void Clear ();
		bool Contains (ITypeReference value);
		bool Contains (string fullName);
		int IndexOf (ITypeReference value);
		void Remove (ITypeReference value);
		void RemoveAt (int index);
	}
}
