/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Fri Feb 25 23:29:17 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

    using System.Collections;

    public interface IModuleReferenceCollection : ICollection, IReflectionStructureVisitable {

        IModuleReference this [int index] { get; }

        IModuleDefinition Container { get; }

        void Clear ();
        bool Contains (IModuleReference value);
        int IndexOf (IModuleReference value);
        void Insert (int index, IModuleReference value);
        void Remove (IModuleReference value);
        void RemoveAt (int index);
    }
}
