/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Aug 25 05:37:45 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

	using System;
	using System.Collections;

	public class NestedTypeEventArgs : EventArgs {

		private ITypeDefinition m_item;

		public ITypeDefinition NestedType {
			get { return m_item; }
		}

		public NestedTypeEventArgs (ITypeDefinition item)
		{
			m_item = item;
		}
	}

	public delegate void NestedTypeEventHandler (
		object sender, NestedTypeEventArgs ea);

	public interface INestedTypeCollection : ICollection, IReflectionVisitable {

		ITypeDefinition this [int index] { get; }

		ITypeDefinition Container { get; }

		event NestedTypeEventHandler OnNestedTypeAdded;
		event NestedTypeEventHandler OnNestedTypeRemoved;

		void Add (ITypeDefinition value);
		void Clear ();
		bool Contains (ITypeDefinition value);
		int IndexOf (ITypeDefinition value);
		void Insert (int index, ITypeDefinition value);
		void Remove (ITypeDefinition value);
		void RemoveAt (int index);
	}
}
