/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Aug 25 05:37:44 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

	using System;
	using System.Collections;

	public class OverrideEventArgs : EventArgs {

		private IMethodReference m_item;

		public IMethodReference Override {
			get { return m_item; }
		}

		public OverrideEventArgs (IMethodReference item)
		{
			m_item = item;
		}
	}

	public delegate void OverrideEventHandler (
		object sender, OverrideEventArgs ea);

	public interface IOverrideCollection : ICollection, IReflectionVisitable {

		IMethodReference this [int index] { get; }

		IMethodDefinition Container { get; }

		event OverrideEventHandler OnOverrideAdded;
		event OverrideEventHandler OnOverrideRemoved;

		void Add (IMethodReference value);
		void Clear ();
		bool Contains (IMethodReference value);
		int IndexOf (IMethodReference value);
		void Insert (int index, IMethodReference value);
		void Remove (IMethodReference value);
		void RemoveAt (int index);
	}
}
