/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Sat Feb 12 06:05:00 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

    using System.Collections;

    public interface IParameterDefinitionCollection : ICollection, IReflectionVisitable {

        IParameterDefinition this [int index] { get; set; }
        
        void Add (IParameterDefinition value);
        void Clear ();
        bool Contains (IParameterDefinition value);
        int IndexOf (IParameterDefinition value);
        void Insert (int index, IParameterDefinition value);
        void Remove (IParameterDefinition value);
        void RemoveAt (int index);
    }
}
