/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Aug 25 05:37:44 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

	using System;
	using System.Collections;

	public class ParameterDefinitionEventArgs : EventArgs {

		private IParameterDefinition m_item;

		public IParameterDefinition ParameterDefinition {
			get { return m_item; }
		}

		public ParameterDefinitionEventArgs (IParameterDefinition item)
		{
			m_item = item;
		}
	}

	public delegate void ParameterDefinitionEventHandler (
		object sender, ParameterDefinitionEventArgs ea);

	public interface IParameterDefinitionCollection : ICollection, IReflectionVisitable {

		IParameterDefinition this [int index] { get; }

		IMemberReference Container { get; }

		event ParameterDefinitionEventHandler OnParameterDefinitionAdded;
		event ParameterDefinitionEventHandler OnParameterDefinitionRemoved;

		void Add (IParameterDefinition value);
		void Clear ();
		bool Contains (IParameterDefinition value);
		int IndexOf (IParameterDefinition value);
		void Insert (int index, IParameterDefinition value);
		void Remove (IParameterDefinition value);
		void RemoveAt (int index);
	}
}
