/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Tue Aug 16 04:10:02 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

	using System.Collections;

	public interface IPropertyDefinitionCollection : ICollection, IReflectionVisitable {

		IPropertyDefinition this [int index] { get; set; }

		ITypeDefinition Container { get; }

		void Add (IPropertyDefinition value);
		void Clear ();
		bool Contains (IPropertyDefinition value);
		int IndexOf (IPropertyDefinition value);
		void Insert (int index, IPropertyDefinition value);
		void Remove (IPropertyDefinition value);
		void RemoveAt (int index);
	}
}
