/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Wed Jan 19 14:17:35 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

    using System.Collections;

    public interface IResourceCollection : ICollection, IReflectionStructureVisitable {

        IResource this [string name] { get; set; }

        IModuleDefinition Container { get; }

        void Clear ();
        bool Contains (IResource value);
        void Remove (IResource value);
    }
}
