/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Aug 25 05:37:45 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

	using System;
	using System.Collections;

	public class ResourceEventArgs : EventArgs {

		private IResource m_item;

		public IResource Resource {
			get { return m_item; }
		}

		public ResourceEventArgs (IResource item)
		{
			m_item = item;
		}
	}

	public delegate void ResourceEventHandler (
		object sender, ResourceEventArgs ea);

	public interface IResourceCollection : ICollection, IReflectionStructureVisitable {

		IResource this [int index] { get; }

		IModuleDefinition Container { get; }

		event ResourceEventHandler OnResourceAdded;
		event ResourceEventHandler OnResourceRemoved;

		void Add (IResource value);
		void Clear ();
		bool Contains (IResource value);
		int IndexOf (IResource value);
		void Insert (int index, IResource value);
		void Remove (IResource value);
		void RemoveAt (int index);
	}
}
