/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Tue Feb 15 23:26:16 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

    using System.Collections;

    public interface ISecurityDeclarationCollection : ICollection, IReflectionVisitable {

        ISecurityDeclaration this [int index] { get; set; }
        
        IHasSecurity Container { get; }
        
        void Add (ISecurityDeclaration value);
        void Clear ();
        bool Contains (ISecurityDeclaration value);
        int IndexOf (ISecurityDeclaration value);
        void Insert (int index, ISecurityDeclaration value);
        void Remove (ISecurityDeclaration value);
        void RemoveAt (int index);
    }
}
