/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Thu Aug 25 04:18:25 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

	using System;
	using System.Collections;

	public class TypeDefinitionEventArgs : EventArgs {

		private ITypeDefinition m_item;

		public ITypeDefinition TypeDefinition {
			get { return m_item; }
		}

		public TypeDefinitionEventArgs (ITypeDefinition item)
		{
			m_item = item;
		}
	}

	public delegate void TypeDefinitionEventHandler (
		object sender, TypeDefinitionEventArgs ea);

	public interface ITypeDefinitionCollection : ICollection, IReflectionVisitable {

		ITypeDefinition this [int index] { get; }
		ITypeDefinition this [string fullName] { get; }

		IModuleDefinition Container { get; }

		event TypeDefinitionEventHandler OnTypeDefinitionAdded;
		event TypeDefinitionEventHandler OnTypeDefinitionRemoved;

		void Add (ITypeDefinition value);
		void Clear ();
		bool Contains (ITypeDefinition value);
		bool Contains (string fullName);
		int IndexOf (ITypeDefinition value);
		void Remove (ITypeDefinition value);
		void RemoveAt (int index);
	}
}
