/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Fri Aug 19 18:04:41 CEST 2005
 *
 *****************************************************************************/

namespace Mono.Cecil {

	using System.Collections;

	public interface ITypeDefinitionCollection : ICollection, IReflectionVisitable {

		ITypeDefinition this [int index] { get; }
		ITypeDefinition this [string fullName] { get; }

		IModuleDefinition Container { get; }

		void Add (ITypeDefinition value);
		void Clear ();
		bool Contains (ITypeDefinition value);
		bool Contains (string fullName);
		int IndexOf (ITypeDefinition value);
		void Remove (ITypeDefinition value);
		void RemoveAt (int index);
	}
}
