//
// Gendarme.Rules.Performance.AvoidUninstantiatedInternalClassesRule
//
// Authors:
//	Nidhi Rawal <sonu2404@gmail.com>
//	Sebastien Pouliot <sebastien@ximian.com>
//
// Copyright (c) <2007> Nidhi Rawal
// Copyright (C) 2007 Novell, Inc (http://www.novell.com)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using System.Collections;

using Mono.Cecil;
using Mono.Cecil.Cil;
using Gendarme.Framework;

namespace Gendarme.Rules.Performance {

	public class AvoidUninstantiatedInternalClassesRule: ITypeRule {

		// FIXME: this should be a global shared method (in the future)
		private bool HasAttribute (CustomAttributeCollection cac, string fullname)
		{
			foreach (CustomAttribute custom in cac) {
				if (custom.Constructor.DeclaringType.FullName == fullname)
					return true;
			}
			return false;
		}

		private bool IsGeneratedByCompiler (TypeReference type)
		{
			return HasAttribute (type.CustomAttributes, "System.Runtime.CompilerServices.CompilerGeneratedAttribute");
		}

		private bool CheckSpecialTypes (TypeDefinition type)
		{
			// <Module> isn't tagged as generated by the compiler but still must be ignored
			if (type.Name == Constants.ModuleType)
				return true;

			// some stuff, like arrays, is nested under <PrivateImplementationDetails>
			if (type.IsNested)
				return IsGeneratedByCompiler (type.DeclaringType);

			return IsGeneratedByCompiler (type);
		}

		public MessageCollection CheckType (TypeDefinition type, Runner runner)
		{
			// rule apply to non-public types
			if (type.IsPublic)
				return runner.RuleSuccess;

			// some types are created by compilers and should be ignored
			if (CheckSpecialTypes (type))
				return runner.RuleSuccess;

			// rule doesn't apply if the assembly open up itself to others using [InternalsVisibleTo]
			if (ImplementsInternalsVisibleToAttribute (type))
				return runner.RuleSuccess;

			if (IsInstantiable (type) && !IsInstantiated (type, type)) {
				Location location = new Location (type.FullName, null);
				Message message = new Message ("There is no call for any of the types constructor found", location, MessageType.Error);
				return new MessageCollection (message);
			}

			return runner.RuleSuccess;
		}

		private bool ImplementsInternalsVisibleToAttribute (TypeDefinition type)
		{
			return HasAttribute (type.Module.Assembly.CustomAttributes,
				"System.Runtime.CompilerServices.InternalsVisibleToAttribute");
		}

		private bool IsInstantiable (TypeDefinition type)
		{
			// note: that also excludes static types (2.0)
			return !type.IsAbstract;
		}

		private bool IsInstantiated (TypeDefinition type, TypeDefinition nestedType)
		{
			bool instantiated = false;

			foreach (MethodDefinition method in nestedType.Methods)
				foreach (Instruction ins in method.Body.Instructions)
					if (ins.OpCode == OpCodes.Newobj) {
						string [] typeName = ins.Operand.ToString ().Split (':');
						if (("System.Void "+ type.FullName) == typeName [0])
							if (MethodIsCalled (nestedType, method))
								instantiated = true;
					}

			if (nestedType.NestedTypes.Count > 0)
				foreach (TypeDefinition nested in type.NestedTypes)
					instantiated = IsInstantiated (type, nested);
			return instantiated;
		}

		private bool MethodIsCalled (TypeDefinition type, MethodDefinition callingMethod)
		{
			string strCallingMethod = String.Empty;

//FIXME: use a IsMain kind of method
			if (callingMethod.Name == "Main" && callingMethod.IsStatic && callingMethod.ReturnType.ReturnType.FullName == "System.Void" && callingMethod.Parameters.Count == 1 && callingMethod.Parameters [0].ParameterType.FullName == "System.String[]")
				return true;
			else
			{
				strCallingMethod = callingMethod.ReturnType.ReturnType.FullName + " " + callingMethod.DeclaringType + "::" + callingMethod.Name + "(";
				foreach (ParameterDefinition parameter in callingMethod.Parameters)
					strCallingMethod += parameter.ParameterType.FullName + ",";

				strCallingMethod = strCallingMethod.Remove (strCallingMethod.Length-1, 1) + ")";

				foreach (MethodDefinition method in type.Methods)
					foreach (Instruction ins in method.Body.Instructions)
						if (ins.OpCode == OpCodes.Call || ins.OpCode == OpCodes.Calli || ins.OpCode == OpCodes.Callvirt)
							if (strCallingMethod == ins.Operand.ToString ())
								return true;
			}
			return false;
		}
	}
}
