/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Tue Jul 05 15:48:33 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Cil {

	using System.Collections;

	public interface IInstructionCollection : ICollection, ICodeVisitable {

		IInstruction this [int index] { get; }

		IMethodBody Container { get; }

		void Clear ();
		bool Contains (IInstruction value);
		int IndexOf (IInstruction value);
		void Insert (int index, IInstruction value);
		void Remove (IInstruction value);
		void RemoveAt (int index);
	}
}
