/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * Sat Feb 12 06:06:34 Paris, Madrid 2005
 *
 *****************************************************************************/

namespace Mono.Cecil.Cil {

    using System.Collections;

    public interface IVariableDefinitionCollection : ICollection, ICodeVisitable {

        IVariableDefinition this [int index] { get; set; }
        
        void Add (IVariableDefinition value);
        void Clear ();
        bool Contains (IVariableDefinition value);
        int IndexOf (IVariableDefinition value);
        void Insert (int index, IVariableDefinition value);
        void Remove (IVariableDefinition value);
        void RemoveAt (int index);
    }
}
