/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * <%=Time.now%>
 *
 *****************************************************************************/

namespace Mono.Cecil.Metadata {

    internal enum CodedIndex {
<% $coded_indexes.each { |ci|
     if (!ci.requ.nil?) then
         puts("#if #{ci.requ.to_s}")
     end
%>        <%=ci.name%><% if ci != $coded_indexes.last %>,<% end %>
<%
     if (!ci.requ.nil?) then
         puts("#endif")
     end
   }
%>    }
}
