/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * <%=Time.now%>
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

    using System;
    using System.Collections;

    using Mono.Cecil;
    using Mono.Cecil.Cil;

    internal class <%=$cur_coll.name%> : <%=$cur_coll.intf%>, ILazyLoadableCollection {

        private IList m_items;
        private <%=$cur_coll.container_impl%> m_container;

        private bool m_loaded;

        public <%=$cur_coll.type%> this [int index] {
            get {
                <%=$cur_coll.pathtoloader%>.Visit (this);
                return m_items [index] as <%=$cur_coll.type%>;
            }
            set { m_items [index] = value; }
        }

        public <%=$cur_coll.container%> Container {
            get { return m_container; }
        }

        public int Count {
            get {
                <%=$cur_coll.pathtoloader%>.Visit (this);
                return m_items.Count;
            }
        }

        public bool IsSynchronized {
            get { return false; }
        }

        public object SyncRoot {
            get { return this; }
        }

        public bool Loaded {
            get { return m_loaded; }
            set { m_loaded = value; }
        }

        public <%=$cur_coll.name%> (<%=$cur_coll.container_impl%> container)
        {
            m_container = container;
            m_items = new ArrayList ();
        }
        
        public void Add (<%=$cur_coll.type%> value)
        {
            m_items.Add (value);
        }

        public void Clear ()
        {
            m_items.Clear ();
        }

        public bool Contains (<%=$cur_coll.type%> value)
        {
            return m_items.Contains (value);
        }
        
        public int IndexOf (<%=$cur_coll.type%> value)
        {
            <%=$cur_coll.pathtoloader%>.Visit (this);
            return m_items.IndexOf (value);
        }

        public void Insert (int index, <%=$cur_coll.type%> value)
        {
            m_items.Insert (index, value);
        }

        public void Remove (<%=$cur_coll.type%> value)
        {
            m_items.Remove (value);
        }

        public void RemoveAt (int index)
        {
            m_items.Remove (index);
        }

        public void CopyTo (Array ary, int index)
        {
            <%=$cur_coll.pathtoloader%>.Visit (this);
            m_items.CopyTo (ary, index);
        }

        public IEnumerator GetEnumerator ()
        {
            <%=$cur_coll.pathtoloader%>.Visit (this);
            return m_items.GetEnumerator ();
        }

        public void Accept (<%=$cur_coll.visitor%> visitor)
        {
            visitor.<%=$cur_coll.visitThis%> (this);
            <%=$cur_coll.type%> [] items = new <%=$cur_coll.type%> [m_items.Count];
            m_items.CopyTo (items, 0);
            for (int i = 0; i < items.Length; i++)
                items [i].Accept (visitor);
        }
    }
}
