/*
 * Copyright (c) 2004, 2005 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jbevain@gmail.com)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * <%=Time.now%>
 *
 *****************************************************************************/

namespace Mono.Cecil.Implem {

	using System;
	using System.Collections;

	using Mono.Cecil;
	using Mono.Cecil.Cil;

	internal class <%=$cur_coll.name%> : <%=$cur_coll.intf%> {

		private IDictionary m_items;
		private <%=$cur_coll.container%> m_container;

		public <%=$cur_coll.type%> this [string name] {
			get { return m_items [name] as <%=$cur_coll.type%>; }
			set { m_items [name] = value; }
		}

		public <%=$cur_coll.container%> Container {
			get { return m_container; }
		}

		public void Add (string name, <%=$cur_coll.type%> value)
		{
			m_items.Add (name, value);
		}

		public int Count {
			get { return m_items.Count; }
		}

		public bool IsSynchronized {
			get { return false; }
		}

		public object SyncRoot {
			get { return this; }
		}

		public <%=$cur_coll.name%> (<%=$cur_coll.container%> container)
		{
			m_container = container;
			m_items = new Hashtable ();
		}

		public void Clear ()
		{
			m_items.Clear ();
		}

		public bool Contains (<%=$cur_coll.type%> value)
		{
			return m_items.Contains (value);
		}

		public void Remove (<%=$cur_coll.type%> value)
		{
			m_items.Remove (value);
		}

		public void CopyTo (Array ary, int index)
		{
			m_items.Values.CopyTo (ary, index);
		}

		public IEnumerator GetEnumerator ()
		{
			return m_items.Values.GetEnumerator ();
		}
<% if !$cur_coll.visitor.nil? then %>
		public void Accept (<%=$cur_coll.visitor%> visitor)
		{
			visitor.<%=$cur_coll.visitThis%> (this);
		}
<% end %>	}
}
