/*
 * Copyright (c) 2004 DotNetGuru and the individuals listed
 * on the ChangeLog entries.
 *
 * Authors :
 *   Jb Evain   (jb.evain@dotnetguru.org)
 *
 * This is a free software distributed under a MIT/X11 license
 * See LICENSE.MIT file for more details
 *
 * Generated by /CodeGen/cecil-gen.rb do not edit
 * <%=Time.now%>
 *
 *****************************************************************************/

namespace Mono.Cecil.Binary {

    internal sealed class PEOptionalHeader : IHeader, IBinaryVisitable {

        private StandardFieldsHeader m_standardFields;
        private NTSpecificFieldsHeader m_ntSpecificFields;
        private DataDirectoriesHeader m_dataDirectories;

        public StandardFieldsHeader StandardFields {
            get { return m_standardFields; }
            set { m_standardFields = value; }
        }

        public NTSpecificFieldsHeader NTSpecificFields {
            get { return m_ntSpecificFields; }
            set { m_ntSpecificFields = value; }
        }

        public DataDirectoriesHeader DataDirectories {
            get { return m_dataDirectories; }
            set { m_dataDirectories = value; }
        }

        public PEOptionalHeader ()
        {
            m_standardFields = new StandardFieldsHeader ();
            m_ntSpecificFields = new NTSpecificFieldsHeader ();
            m_dataDirectories = new DataDirectoriesHeader ();
        }

        public void SetDefaultValues ()
        {
        }

        public void Accept (IBinaryVisitor visitor)
        {
            visitor.Visit (this);

            m_standardFields.Accept (visitor);
            m_ntSpecificFields.Accept (visitor);
            m_dataDirectories.Accept (visitor);
        }
        <% header = $headers["PEOptionalHeader.StandardFieldsHeader"] %>
        public sealed class StandardFieldsHeader : IHeader, IBinaryVisitable {

<% header.fields.each { |f| %>            private <%=f.type%> <%=f.field_name%>;<% print("\n") } %>

<% header.fields.each { |f| %>            public <%=f.type%> <%=f.property_name%> {
                get { return <%=f.field_name%>; }
                set { <%=f.field_name%> = value; }
            }
<% print("\n") } %>            public StandardFieldsHeader ()
            {
            }

            public void SetDefaultValues ()
            {<% header.fields.each { |f| print("\n                " +  f.field_name + " = " + f.default + ";") unless f.default.nil? } %>
            }

            public void Accept (IBinaryVisitor visitor)
            {
                visitor.Visit (this);
            }
        }
        <% header = $headers["PEOptionalHeader.NTSpecificFieldsHeader"] %>
        public sealed class NTSpecificFieldsHeader : IHeader, IBinaryVisitable {

<% header.fields.each { |f| %>            private <%=f.type%> <%=f.field_name%>;<% print("\n") } %>

<% header.fields.each { |f| %>            public <%=f.type%> <%=f.property_name%> {
                get { return <%=f.field_name%>; }
                set { <%=f.field_name%> = value; }
            }
<% print("\n") } %>            public NTSpecificFieldsHeader ()
            {
            }

            public void SetDefaultValues ()
            {<% header.fields.each { |f| print("\n                " +  f.field_name + " = " + f.default + ";") unless f.default.nil? } %>
            }

            public void Accept (IBinaryVisitor visitor)
            {
                visitor.Visit (this);
            }
        }
        <% header = $headers["PEOptionalHeader.DataDirectoriesHeader"] %>
        public sealed class DataDirectoriesHeader : IHeader, IBinaryVisitable {

<% header.fields.each { |f| %>            private <%=f.type%> <%=f.field_name%>;<% print("\n") } %>

<% header.fields.each { |f| %>            public <%=f.type%> <%=f.property_name%> {
                get { return <%=f.field_name%>; }
                set { <%=f.field_name%> = value; }
            }
<% print("\n") } %>            public DataDirectoriesHeader ()
            {
            }

            public void SetDefaultValues ()
            {<% header.fields.each { |f| print("\n                " +  f.field_name + " = " + f.default + ";") unless f.default.nil? } %>
            }

            public void Accept (IBinaryVisitor visitor)
            {
                visitor.Visit (this);
            }
        }
    }
}
